version: "3.4"

services:
  keycloak:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: ${DB_ADDR}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_SCHEMA: public
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_PRIVATE_ADDRESS: ${JGROUPS_PRIVATE_ADDRESS}
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - 8080:8080
      - 7600:7600
      - 57600:57600
