version: "3.4"

services:
  keycloak:
    build:
      context: ./
      dockerfile: infrastructure/docker/keycloak/Dockerfile
      target: dev
    volumes:
      - ./themes/noi:/opt/jboss/keycloak/themes/noi
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - internal
      - authentication

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - internal

networks:
  authentication:
    external: true
  internal:
    external: false
