version: "3.4"

services:
  keycloak:
    build:
      context: ./
      dockerfile: docker/keycloak/Dockerfile
      # target: dev
    volumes:
      - ./themes/noi:/opt/jboss/keycloak/themes/noi
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_FRONTEND_URL: https://auth.aboutbits.local/auth
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - internal
      - proxy
    labels:
      - traefik.api.frontend.rule=Host:auth.aboutbits.local
      - traefik.docker.network=proxy
      - traefik.port=8080
      - traefik.backend=auth

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - internal
    labels:
      - traefik.enable=false

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - internal
    labels:
      - traefik.enable=false

networks:
  proxy:
    external: true
  internal:
    external: false
