version: "3.4"

services:
  keycloak:
    build:
      context: ./
      dockerfile: docker/keycloak/Dockerfile
      target: dev
    volumes:
      - ./themes/noi:/opt/jboss/keycloak/themes/noi
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
