version: "3.4"

services:
  keycloak:
    image: jboss/keycloak
    volumes:
      - ./:/code:cached
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
